name: HayCam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  gallery_saver: ^2.3.2
  image: ^4.2.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  open_settings: ^2.0.2
  path_provider: ^2.1.3
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  toggle_switch: ^2.3.0
  video_player: ^2.9.1
  widget_zoom: ^0.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/haycam.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
